# Font
font_family JetBrains Mono Nerd Font
font_size 11.0

# Cursor
cursor_shape beam
cursor_blink yes
cursor_blink_interval 0.5 ease-in-out

# Cursor trail
cursor_trail 50
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Scrollback
scrollback_lines 10000

# WINDOW & RENDERING
hide_window_decorations yes
# background_opacity 0.8

# Text rendering strategy: can be 'auto', 'simple', 'complex', 'legacy'
text_composition_strategy legacy

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
