# config in etc/snapserver.conf

context.modules = [
  { name = libpipewire-module-pipe-tunnel
    args = {
      node.name = "snapcast"
      node.description = "Snapcast"
      tunnel.mode = sink
      pipe.filename = "/tmp/snapfifo"
      audio.format = S16LE
      audio.rate = 48000
      audio.channels = 2
    }
  }
]
