return {
  { import = "plugins.catppuccin" },
  { import = "plugins.cmp" },
  { import = "plugins.lsp" },
  { import = "plugins.arborist" },
  { import = "plugins.mason" },
  { import = "plugins.lsp_lines" },
  { import = "plugins.formatters" },
  { import = "plugins.autopairs" },
  { import = "plugins.explorer" },
  { import = "plugins.telescope" },
  { import = "plugins.lualine" },
  { import = "plugins.gitsigns" },
  { import = "plugins.diffview" },
  { import = "plugins.comment" },
  { import = "plugins.whichkey" },
  { import = "plugins.luasnip" },
  { import = "plugins.aerial" },
  { import = "plugins.gitconflict" },
  { import = "plugins.undotree" },
  { import = "plugins.bufferline" },
  { import = "plugins.fugitive" },
  { import = "plugins.virt-column" },
  { import = "plugins.blankline" },
  { import = "plugins.navic" },
  { import = "plugins.surround" },
  { import = "plugins.minuet" },
}
